### ISSUE TITLE
outdated info / improvements

### ISSUE THREAD

**Issue by maskersss** [sathya-pramodh/linux-mcsr#10]
- https://sathya-pramodh.github.io/linux-mcsr/minecraft/resetti.html: i'm assuming resetti got replaced by seedqueue for multiinstance, though i'm assuming it still has useful functionality?
- https://sathya-pramodh.github.io/linux-mcsr/perf/jemalloc_glfw.html: glfw 3.3.8 crashes with lwjgl 3.3.x, idk if meta is to just use newer lwjgl (harder on mmc than prism) or old lwjgl with new glfw, but would be worth mentioning anyway
- https://sathya-pramodh.github.io/linux-mcsr/minecraft/mmc.html would prob be nice to mention enabling Skip Java compatibility checks in prism, i.e. "Prism Launcher will tell you to use Java 8 for 1.16.1. For speedrunning, using the latest Java version is fine and recommended, so you should enable `Skip Java compatibility checks`"
- https://sathya-pramodh.github.io/linux-mcsr/index.html: `You can get started right here.` links to index.html instead of introduction.html

i was considering opening a pr but i figured idk what i'm talking about for the first two things and the latter two are minor

**Comment by sathya-pramodh** [comment]
1. I want to rewrite this section someday... I just want to mention seedqueue here along with resetti for resolution stuff. But also have a link to the final wall release of resetti if someone wants to use it.

2. I want to rewrite this as well. Priffin and I found a very neat little fix for making glfw work without needing the patch on any version (I currently am using this fix and it works flawlessly).

3. That's a good shout, will fix when I do the above rewrites.

4. This was intended because it is meant to redirect people to the website when clicking in from GitHub. You would need to use the mdbook navs to do your navigation while on the website. But ig most links in Pingu bot etc are into the website itself. Probably would rename it to something like `Click` here to get to the website or something along those lines.

:D Thanks for noticing all this.. i appreciate you <3

**Comment by sathya-pramodh** [comment]
I have updated the stuff in the latest commit 299ec3aab8651f31ea25da71e576930b7422f4d7
